name = "Optim"
uuid = "429524aa-4258-5aef-a3af-852621145aeb"
version = "0.19.2"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
DiffEqDiffTools = "01453d9d-ee7c-5054-8395-0335cb756afa"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Calculus = "≥ 0.4"
DiffEqDiffTools = "≥ 0.12"
FillArrays = "0.6.2"
ForwardDiff = "0.10.3"
LineSearches = "7.0.1"
NLSolversBase = "7.3.1"
NaNMath = "0.3.2"
Parameters = "0.10"
PositiveFactorizations = "0.2.2"
julia = "1"

[extras]
OptimTestProblems = "cec144fc-5a64-5bc6-99fb-dde8f63e154c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OptimTestProblems", "Suppressor", "RecursiveArrayTools"]
